# Generated by Django 3.1.2 on 2021-03-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_of_month',
            field=models.BooleanField(default=0),
        ),
    ]
